services:
  - type: web
    name: controle-interno
    runtime: docker
    plan: free
    repo: https://github.com/fabianopoleto/Controle-interno-BA
    branch: main
    envVars:
      - key: PORT
        value: 8080
