spring.datasource.url=jdbc:postgresql://postgresql://admin:lGBajyn5U50VSXYQ0UTq8YJF3pVVfPGQ@dpg-d4ahoemuk2gs739f9ucg-a.oregon-postgres.render.com/controleinterno
spring.datasource.username=admin
spring.datasource.password=lGBajyn5U50VSXYQ0UTq8YJF3pVVfPGQ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

